name: linuxman
description: Linux Command Manual (Chinese Simplified Edition)
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  archive: ^3.1.2
  path_provider: ^2.0.2
  flutter_markdown: ^0.6.2
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/